version: 2

formats: []

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv venv
    - uv pip install mkdocs mkdocs-material
    - uv pip install mkdocstrings mkdocstrings-python
    - uv pip install mkdocs-awesome-pages-plugin mkdocs-autorefs
    - uv pip install -e .
    - .venv/bin/python -m mkdocs build --site-dir $READTHEDOCS_OUTPUT/html
